version: '3'
services:
  app:
    build: .
    container_name: go-profiles
    environment: 
        PROFILES_SERVER_PORT: "8080"
        PROFILES_SERVER_HOST: "0.0.0.0"
        PROFILES_DB_HOSTNAME: "cluster0.3xaks.mongodb.net"
        PROFILES_DB_USERNAME: "profile"
        PROFILES_DB_PASSWORD: "${PROFILES_DB_PASSWORD}"
        PROFILES_DB_PROTOCOL: "mongodb+srv"
        SCOPE: "local"
    ports:
      - "8080:8080"
